trigger:
  branches:
    exclude:
      - feature*
      - NOJIRA*
      - nojira*
      - czirjak*

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: git_configurations


steps:
  - task: InstallSSHKey@0
    inputs:
      knownHostsEntry: $(knownHosts)
      sshPublicKey: $(publicKey)
      sshKeySecureFile: 'id_rsa'
    displayName: 'Install SSH'
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '17'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'
    displayName: 'Install Java 21'
  - task: DockerInstaller@0
    inputs:
      dockerVersion: '20.10.21'
    displayName: 'Install Docker'
  - script: |
      ./gradlew clean
      ./gradlew check
    displayName: 'Compile & test & check'
  - script: |
      ./gradlew build -x check --info
    displayName: 'Create jar'
  - script: |
      ./gradlew buildDockerImageAsLatest --info
      docker images
    displayName: 'Create docker image'
  - task: Docker@2
    inputs:
      containerRegistry: 'docker'
      repository: 'matemorvai21/servicec_remake'
      command: 'buildAndPush'
      Dockerfile: '**/form-service/build/libs/Dockerfile'
      tags: '$(Build.BuildId)'
    displayName: 'Push Docker Hub'
